// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xsimons_idwt.h"

extern XSimons_idwt_Config XSimons_idwt_ConfigTable[];

XSimons_idwt_Config *XSimons_idwt_LookupConfig(u16 DeviceId) {
	XSimons_idwt_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSIMONS_IDWT_NUM_INSTANCES; Index++) {
		if (XSimons_idwt_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XSimons_idwt_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XSimons_idwt_Initialize(XSimons_idwt *InstancePtr, u16 DeviceId) {
	XSimons_idwt_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XSimons_idwt_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XSimons_idwt_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

