// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xsimons_idwt.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XSimons_idwt_CfgInitialize(XSimons_idwt *InstancePtr, XSimons_idwt_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XSimons_idwt_Start(XSimons_idwt *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSimons_idwt_ReadReg(InstancePtr->Control_bus_BaseAddress, XSIMONS_IDWT_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XSimons_idwt_WriteReg(InstancePtr->Control_bus_BaseAddress, XSIMONS_IDWT_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XSimons_idwt_IsDone(XSimons_idwt *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSimons_idwt_ReadReg(InstancePtr->Control_bus_BaseAddress, XSIMONS_IDWT_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XSimons_idwt_IsIdle(XSimons_idwt *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSimons_idwt_ReadReg(InstancePtr->Control_bus_BaseAddress, XSIMONS_IDWT_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XSimons_idwt_IsReady(XSimons_idwt *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSimons_idwt_ReadReg(InstancePtr->Control_bus_BaseAddress, XSIMONS_IDWT_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XSimons_idwt_EnableAutoRestart(XSimons_idwt *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSimons_idwt_WriteReg(InstancePtr->Control_bus_BaseAddress, XSIMONS_IDWT_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XSimons_idwt_DisableAutoRestart(XSimons_idwt *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSimons_idwt_WriteReg(InstancePtr->Control_bus_BaseAddress, XSIMONS_IDWT_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XSimons_idwt_InterruptGlobalEnable(XSimons_idwt *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSimons_idwt_WriteReg(InstancePtr->Control_bus_BaseAddress, XSIMONS_IDWT_CONTROL_BUS_ADDR_GIE, 1);
}

void XSimons_idwt_InterruptGlobalDisable(XSimons_idwt *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSimons_idwt_WriteReg(InstancePtr->Control_bus_BaseAddress, XSIMONS_IDWT_CONTROL_BUS_ADDR_GIE, 0);
}

void XSimons_idwt_InterruptEnable(XSimons_idwt *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSimons_idwt_ReadReg(InstancePtr->Control_bus_BaseAddress, XSIMONS_IDWT_CONTROL_BUS_ADDR_IER);
    XSimons_idwt_WriteReg(InstancePtr->Control_bus_BaseAddress, XSIMONS_IDWT_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XSimons_idwt_InterruptDisable(XSimons_idwt *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSimons_idwt_ReadReg(InstancePtr->Control_bus_BaseAddress, XSIMONS_IDWT_CONTROL_BUS_ADDR_IER);
    XSimons_idwt_WriteReg(InstancePtr->Control_bus_BaseAddress, XSIMONS_IDWT_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XSimons_idwt_InterruptClear(XSimons_idwt *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSimons_idwt_WriteReg(InstancePtr->Control_bus_BaseAddress, XSIMONS_IDWT_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XSimons_idwt_InterruptGetEnabled(XSimons_idwt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSimons_idwt_ReadReg(InstancePtr->Control_bus_BaseAddress, XSIMONS_IDWT_CONTROL_BUS_ADDR_IER);
}

u32 XSimons_idwt_InterruptGetStatus(XSimons_idwt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSimons_idwt_ReadReg(InstancePtr->Control_bus_BaseAddress, XSIMONS_IDWT_CONTROL_BUS_ADDR_ISR);
}

