// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XIDWT_H
#define XIDWT_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xidwt_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_bus_BaseAddress;
} XIdwt_Config;
#endif

typedef struct {
    u32 Control_bus_BaseAddress;
    u32 IsReady;
} XIdwt;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XIdwt_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XIdwt_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XIdwt_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XIdwt_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XIdwt_Initialize(XIdwt *InstancePtr, u16 DeviceId);
XIdwt_Config* XIdwt_LookupConfig(u16 DeviceId);
int XIdwt_CfgInitialize(XIdwt *InstancePtr, XIdwt_Config *ConfigPtr);
#else
int XIdwt_Initialize(XIdwt *InstancePtr, const char* InstanceName);
int XIdwt_Release(XIdwt *InstancePtr);
#endif

void XIdwt_Start(XIdwt *InstancePtr);
u32 XIdwt_IsDone(XIdwt *InstancePtr);
u32 XIdwt_IsIdle(XIdwt *InstancePtr);
u32 XIdwt_IsReady(XIdwt *InstancePtr);
void XIdwt_EnableAutoRestart(XIdwt *InstancePtr);
void XIdwt_DisableAutoRestart(XIdwt *InstancePtr);

void XIdwt_Set_imageIn0(XIdwt *InstancePtr, u32 Data);
u32 XIdwt_Get_imageIn0(XIdwt *InstancePtr);
void XIdwt_Set_imageIn1(XIdwt *InstancePtr, u32 Data);
u32 XIdwt_Get_imageIn1(XIdwt *InstancePtr);
void XIdwt_Set_imageIn2(XIdwt *InstancePtr, u32 Data);
u32 XIdwt_Get_imageIn2(XIdwt *InstancePtr);
void XIdwt_Set_imageIn3(XIdwt *InstancePtr, u32 Data);
u32 XIdwt_Get_imageIn3(XIdwt *InstancePtr);
void XIdwt_Set_imageOut(XIdwt *InstancePtr, u32 Data);
u32 XIdwt_Get_imageOut(XIdwt *InstancePtr);

void XIdwt_InterruptGlobalEnable(XIdwt *InstancePtr);
void XIdwt_InterruptGlobalDisable(XIdwt *InstancePtr);
void XIdwt_InterruptEnable(XIdwt *InstancePtr, u32 Mask);
void XIdwt_InterruptDisable(XIdwt *InstancePtr, u32 Mask);
void XIdwt_InterruptClear(XIdwt *InstancePtr, u32 Mask);
u32 XIdwt_InterruptGetEnabled(XIdwt *InstancePtr);
u32 XIdwt_InterruptGetStatus(XIdwt *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
