// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xidwt.h"

extern XIdwt_Config XIdwt_ConfigTable[];

XIdwt_Config *XIdwt_LookupConfig(u16 DeviceId) {
	XIdwt_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XIDWT_NUM_INSTANCES; Index++) {
		if (XIdwt_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XIdwt_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XIdwt_Initialize(XIdwt *InstancePtr, u16 DeviceId) {
	XIdwt_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XIdwt_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XIdwt_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

