// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xsimons_dwt.h"

extern XSimons_dwt_Config XSimons_dwt_ConfigTable[];

XSimons_dwt_Config *XSimons_dwt_LookupConfig(u16 DeviceId) {
	XSimons_dwt_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSIMONS_DWT_NUM_INSTANCES; Index++) {
		if (XSimons_dwt_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XSimons_dwt_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XSimons_dwt_Initialize(XSimons_dwt *InstancePtr, u16 DeviceId) {
	XSimons_dwt_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XSimons_dwt_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XSimons_dwt_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

