// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xidwt.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XIdwt_CfgInitialize(XIdwt *InstancePtr, XIdwt_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XIdwt_Start(XIdwt *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XIdwt_ReadReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XIdwt_WriteReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XIdwt_IsDone(XIdwt *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XIdwt_ReadReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XIdwt_IsIdle(XIdwt *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XIdwt_ReadReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XIdwt_IsReady(XIdwt *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XIdwt_ReadReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XIdwt_EnableAutoRestart(XIdwt *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XIdwt_WriteReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XIdwt_DisableAutoRestart(XIdwt *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XIdwt_WriteReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XIdwt_Set_imageIn0(XIdwt *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XIdwt_WriteReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_IMAGEIN0_DATA, Data);
}

u32 XIdwt_Get_imageIn0(XIdwt *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XIdwt_ReadReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_IMAGEIN0_DATA);
    return Data;
}

void XIdwt_Set_imageIn1(XIdwt *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XIdwt_WriteReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_IMAGEIN1_DATA, Data);
}

u32 XIdwt_Get_imageIn1(XIdwt *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XIdwt_ReadReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_IMAGEIN1_DATA);
    return Data;
}

void XIdwt_Set_imageIn2(XIdwt *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XIdwt_WriteReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_IMAGEIN2_DATA, Data);
}

u32 XIdwt_Get_imageIn2(XIdwt *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XIdwt_ReadReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_IMAGEIN2_DATA);
    return Data;
}

void XIdwt_Set_imageIn3(XIdwt *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XIdwt_WriteReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_IMAGEIN3_DATA, Data);
}

u32 XIdwt_Get_imageIn3(XIdwt *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XIdwt_ReadReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_IMAGEIN3_DATA);
    return Data;
}

void XIdwt_Set_imageOut(XIdwt *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XIdwt_WriteReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_IMAGEOUT_DATA, Data);
}

u32 XIdwt_Get_imageOut(XIdwt *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XIdwt_ReadReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_IMAGEOUT_DATA);
    return Data;
}

void XIdwt_InterruptGlobalEnable(XIdwt *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XIdwt_WriteReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_GIE, 1);
}

void XIdwt_InterruptGlobalDisable(XIdwt *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XIdwt_WriteReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_GIE, 0);
}

void XIdwt_InterruptEnable(XIdwt *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XIdwt_ReadReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_IER);
    XIdwt_WriteReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XIdwt_InterruptDisable(XIdwt *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XIdwt_ReadReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_IER);
    XIdwt_WriteReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XIdwt_InterruptClear(XIdwt *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XIdwt_WriteReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XIdwt_InterruptGetEnabled(XIdwt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XIdwt_ReadReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_IER);
}

u32 XIdwt_InterruptGetStatus(XIdwt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XIdwt_ReadReg(InstancePtr->Control_bus_BaseAddress, XIDWT_CONTROL_BUS_ADDR_ISR);
}

