// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xdwt.h"

extern XDwt_Config XDwt_ConfigTable[];

XDwt_Config *XDwt_LookupConfig(u16 DeviceId) {
	XDwt_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XDWT_NUM_INSTANCES; Index++) {
		if (XDwt_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XDwt_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XDwt_Initialize(XDwt *InstancePtr, u16 DeviceId) {
	XDwt_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XDwt_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XDwt_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

